"""Resi not nullable i campi attivita_svolta, date e volontari_impiegati

Revision ID: 02befed9a6b0
Revises: 4746c74acdef
Create Date: 2025-07-25 19:44:56.966447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02befed9a6b0'
down_revision = '4746c74acdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.alter_column('attivita_svolta',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('data_inizio_attivita',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('data_fine_attivita',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('volontari_impiegati',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.alter_column('volontari_impiegati',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('data_fine_attivita',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('data_inizio_attivita',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('attivita_svolta',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
