"""aggiunto campo nota_istruttoria alla tabella spese

Revision ID: 36a838c5d630
Revises: 02befed9a6b0
Create Date: 2025-07-26 16:53:31.861552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a838c5d630'
down_revision = '02befed9a6b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documenti_spesa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spesa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('SCONTRINO', 'QUIETANZA', 'FATTURA', 'AUTORIZZAZIONE', 'ATTESTAZIONE_DANNO', name='tipodocumento'), nullable=False),
    sa.Column('numero', sa.String(length=100), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descrizione', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('data_modifica', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spesa_id'], ['spese.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spese', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_istruttoria', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spese', schema=None) as batch_op:
        batch_op.drop_column('nota_istruttoria')

    op.drop_table('documenti_spesa')
    # ### end Alembic commands ###
