"""Aggiunto campo nome_file a DocumentoSpesa

Revision ID: 3c29905466dd
Revises: d41baaa0454c
Create Date: 2025-08-18 08:09:27.004909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c29905466dd'
down_revision = 'd41baaa0454c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_spesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_file', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_spesa', schema=None) as batch_op:
        batch_op.drop_column('nome_file')

    # ### end Alembic commands ###
