"""Aggiunta campi per la fase istruttoria

Revision ID: 45bd2c7d3ecc
Revises: 3c29905466dd
Create Date: 2025-08-18 14:35:59.171839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45bd2c7d3ecc'
down_revision = '3c29905466dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documento_spesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verificato', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('note_istruttoria', sa.Text(), nullable=True))

    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_istruttoria', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.drop_column('note_istruttoria')

    with op.batch_alter_table('documento_spesa', schema=None) as batch_op:
        batch_op.drop_column('note_istruttoria')
        batch_op.drop_column('verificato')

    # ### end Alembic commands ###
