"""Aggiunti campi attivita_svolta, date e volontari_impiegati alla tabella richieste

Revision ID: 4746c74acdef
Revises: 7344b4388915
Create Date: 2025-07-25 19:38:17.039678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4746c74acdef'
down_revision = '7344b4388915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attivita_svolta', sa.Text(), nullable=True, comment="Descrizione dettagliata dell'attività svolta"))
        batch_op.add_column(sa.Column('data_inizio_attivita', sa.DateTime(), nullable=True, comment="Data di inizio dell'attività"))
        batch_op.add_column(sa.Column('data_fine_attivita', sa.DateTime(), nullable=True, comment="Data di fine dell'attività"))
        batch_op.add_column(sa.Column('volontari_impiegati', sa.Integer(), nullable=True, comment="Numero di volontari impiegati nell'attività"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richieste', schema=None) as batch_op:
        batch_op.drop_column('volontari_impiegati')
        batch_op.drop_column('data_fine_attivita')
        batch_op.drop_column('data_inizio_attivita')
        batch_op.drop_column('attivita_svolta')

    # ### end Alembic commands ###
