"""Aggiunta tabella di associazione user_odv

Revision ID: 7344b4388915
Revises: c8602570d1de
Create Date: 2025-07-25 19:13:20.981688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7344b4388915'
down_revision = 'c8602570d1de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_odv_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('odv_id', sa.Integer(), nullable=False),
    sa.Column('data_assegnazione', sa.DateTime(), nullable=True),
    sa.Column('assegnato_da', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assegnato_da'], ['user.id'], ),
    sa.ForeignKeyConstraint(['odv_id'], ['odv.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'odv_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_odv_association')
    # ### end Alembic commands ###
