"""Sostituito tipo spesa Parcheggio con Viaggi

Revision ID: a1b2c3d4e5f6
Revises: fb7f918f77e7
Create Date: 2025-07-28 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'fb7f918f77e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Modifica del tipo spesa da PARCHEGGIO a VIAGGI nella tabella spese
    with op.batch_alter_table('spese', schema=None) as batch_op:
        # Aggiorna il tipo di spesa da '05' (PARCHEGGIO) a '07' (VIAGGI)
        op.execute("UPDATE spese SET tipo = '07' WHERE tipo = '05'")
    
    # 2. Modifica della discriminator_type nelle spese polimorfe
    # op.execute("UPDATE spese SET discriminator_type = 'spesa_viaggi' WHERE discriminator_type = 'spesa_parcheggio'")
    
    # 3. Rinomina la colonna 'parcheggio' a 'viaggio' se esiste
    # Questo passaggio potrebbe richiedere adattamenti in base alla struttura effettiva del database
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Ripristina il tipo di spesa da '07' (VIAGGI) a '05' (PARCHEGGIO)
    with op.batch_alter_table('spese', schema=None) as batch_op:
        op.execute("UPDATE spese SET tipo = '05' WHERE tipo = '07'")
    
    # 2. Ripristina la discriminator_type
    # op.execute("UPDATE spese SET discriminator_type = 'spesa_parcheggio' WHERE discriminator_type = 'spesa_viaggi'")
    
    # 3. Rinomina la colonna 'viaggio' a 'parcheggio' se era stata rinominata
    
    # ### end Alembic commands ###
