"""Aggiunta modelli ODV e Mezzo

Revision ID: b63e9441af67
Revises: 
Create Date: 2025-07-25 15:07:42.376795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63e9441af67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odv',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('acronimo', sa.String(length=50), nullable=True),
    sa.Column('provincia', sa.String(length=100), nullable=False),
    sa.Column('comune', sa.String(length=100), nullable=False),
    sa.Column('indirizzo', sa.String(length=255), nullable=False),
    sa.Column('pec', sa.String(length=255), nullable=False),
    sa.Column('recapito_telefonico', sa.String(length=50), nullable=False),
    sa.Column('legale_rappresentante', sa.String(length=255), nullable=False),
    sa.Column('iban', sa.String(length=50), nullable=False),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('data_modifica', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mezzo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odv_id', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.Enum('VEICOLO', 'AUTOCARRO', 'IDROPULITRICE', 'TORREFARO', name='tipologiamezzo'), nullable=False),
    sa.Column('targa_inventario', sa.String(length=50), nullable=False),
    sa.Column('descrizione', sa.String(length=255), nullable=True),
    sa.Column('data_creazione', sa.DateTime(), nullable=True),
    sa.Column('data_modifica', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['odv_id'], ['odv.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mezzo')
    op.drop_table('odv')
    # ### end Alembic commands ###
