"""Aggiunti campi protocollo a Richiesta

Revision ID: b932b21b7260
Revises: 
Create Date: 2025-08-17 10:51:48.160113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b932b21b7260'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_evento')
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.alter_column('spesa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocollo_invio', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('protocollo_istruttoria', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.drop_column('protocollo_istruttoria')
        batch_op.drop_column('protocollo_invio')

    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.alter_column('spesa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    op.create_table('_alembic_tmp_evento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('protocollo_attivazione', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipologia', sa.VARCHAR(length=1), nullable=False),
    sa.Column('data_inizio', sa.DATE(), nullable=True),
    sa.Column('data_fine', sa.DATE(), nullable=True),
    sa.Column('descrizione', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocollo_attivazione')
    )
    # ### end Alembic commands ###
