"""Aggiunto campo_uni  alla richiesta

Revision ID: c45b87f566dd
Revises: 45bd2c7d3ecc
Create Date: 2025-08-22 20:17:25.070832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45b87f566dd'
down_revision = '45bd2c7d3ecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codice_uni', sa.String(length=25), nullable=True))
        batch_op.create_unique_constraint('uq_richiesta_codice_uni', ['codice_uni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('codice_uni')

    # ### end Alembic commands ###
