"""Aggiunti campi protocollo a Richiesta

Revision ID: d2e1e1ed65c2
Revises: 
Create Date: 2025-08-17 10:48:15.077812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2e1e1ed65c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.alter_column('spesa_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocollo_invio', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('protocollo_istruttoria', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['protocollo_invio'])
        batch_op.create_unique_constraint(None, ['protocollo_istruttoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('protocollo_istruttoria')
        batch_op.drop_column('protocollo_invio')

    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.alter_column('spesa_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###
