"""Modelli rinominati e ripristinati

Revision ID: d41baaa0454c
Revises: 
Create Date: 2025-08-17 16:22:31.608309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41baaa0454c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descrizione', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tipologia', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('data_inizio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_fine', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_column('data_fine')
        batch_op.drop_column('data_inizio')
        batch_op.drop_column('tipologia')
        batch_op.drop_column('descrizione')

    # ### end Alembic commands ###
