"""codice_uni NOT NULL

Revision ID: ef9b0ed504a2
Revises: c45b87f566dd
Create Date: 2025-08-22 21:05:34.841179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef9b0ed504a2'
down_revision = 'c45b87f566dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.alter_column('codice_uni',
               existing_type=sa.VARCHAR(length=25),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('richiesta', schema=None) as batch_op:
        batch_op.alter_column('codice_uni',
               existing_type=sa.VARCHAR(length=25),
               nullable=True)

    # ### end Alembic commands ###
