"""Ristrutturazione relazione Spesa-Impiego

Revision ID: f217fd6fece3
Revises: b932b21b7260
Create Date: 2025-08-17 15:38:47.560613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f217fd6fece3'
down_revision = 'b932b21b7260'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('richiesta_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'richiesta', ['richiesta_id'], ['id'])
        batch_op.drop_column('spesa_id')

    with op.batch_alter_table('spesa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('impiego_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'impiego_mezzo_attrezzatura', ['impiego_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spesa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('impiego_id')

    with op.batch_alter_table('impiego_mezzo_attrezzatura', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spesa_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'spesa', ['spesa_id'], ['id'])
        batch_op.drop_column('richiesta_id')

    # ### end Alembic commands ###
