"""Add conducente, localita fields and richiesta_id foreign key to ImpiegoMezzo

Revision ID: fb7f918f77e7
Revises: 36a838c5d630
Create Date: 2025-07-27 08:21:16.580485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7f918f77e7'
down_revision = '36a838c5d630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impiego_mezzo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('richiesta_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conducente', sa.String(length=100), nullable=False, comment='Nome e cognome del conducente del mezzo'))
        batch_op.add_column(sa.Column('localita', sa.String(length=200), nullable=False, comment='Località di utilizzo del mezzo'))
        batch_op.create_foreign_key('fk_impiego_mezzo_richiesta', 'richieste', ['richiesta_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('impiego_mezzo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_impiego_mezzo_richiesta', type_='foreignkey')
        batch_op.drop_column('localita')
        batch_op.drop_column('conducente')
        batch_op.drop_column('richiesta_id')

    # ### end Alembic commands ###
